apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-omp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mpi-omp
  template:
    metadata:
      labels:
        app: mpi-omp
    spec:
      containers:
      - name: mpi-omp
        image: dsousaveras/mpi-omp-k8s:latest
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-omp-service
spec:
  selector:
    app: mpi-omp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
