apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  namespace: space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: dsousaveras/control-center:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: control-center-service
  namespace: space
spec:
  selector:
    app: control-center
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
