apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
        - name: data-processor
          image: dsousaveras/data-processor:latest
          env:
            - name: CONTROL_CENTER_URL
              value: "http://control-center-service:5000"
