FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY control_center.py control_center.py

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "control_center.py"]
